// Generated by gencpp from file xpp_msgs/RobotStateCartesianTrajectory.msg
// DO NOT EDIT!


#ifndef XPP_MSGS_MESSAGE_ROBOTSTATECARTESIANTRAJECTORY_H
#define XPP_MSGS_MESSAGE_ROBOTSTATECARTESIANTRAJECTORY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <xpp_msgs/RobotStateCartesian.h>

namespace xpp_msgs
{
template <class ContainerAllocator>
struct RobotStateCartesianTrajectory_
{
  typedef RobotStateCartesianTrajectory_<ContainerAllocator> Type;

  RobotStateCartesianTrajectory_()
    : header()
    , points()  {
    }
  RobotStateCartesianTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::xpp_msgs::RobotStateCartesian_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::xpp_msgs::RobotStateCartesian_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStateCartesianTrajectory_

typedef ::xpp_msgs::RobotStateCartesianTrajectory_<std::allocator<void> > RobotStateCartesianTrajectory;

typedef boost::shared_ptr< ::xpp_msgs::RobotStateCartesianTrajectory > RobotStateCartesianTrajectoryPtr;
typedef boost::shared_ptr< ::xpp_msgs::RobotStateCartesianTrajectory const> RobotStateCartesianTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator1> & lhs, const ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator1> & lhs, const ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xpp_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf81e80e883d7cf1f8652d3cf7985437";
  }

  static const char* value(const ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf81e80e883d7cf1ULL;
  static const uint64_t static_value2 = 0xf8652d3cf7985437ULL;
};

template<class ContainerAllocator>
struct DataType< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xpp_msgs/RobotStateCartesianTrajectory";
  }

  static const char* value(const ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The state of a robot expressed in the cartesian frame\n"
"\n"
"# The header is used to specify the coordinate frame and the reference time for the trajectory durations\n"
"std_msgs/Header header\n"
"\n"
"# A representation of a Cartesian trajectory\n"
"RobotStateCartesian[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: xpp_msgs/RobotStateCartesian\n"
"# The state of a robot expressed in the Cartesian frame\n"
"\n"
"duration                time_from_start   # global time along trajectory\n"
"\n"
"# Position, velocity and acceleration of the base expressed in world frame\n"
"# The orientation quaternion maps base to world frame.\n"
"State6d                 base              # base pos/vel/acc in world\n"
"\n"
"StateLin3d[]            ee_motion         # endeffector pos/vel/acc in world\n"
"geometry_msgs/Vector3[] ee_forces         # endeffector forces expressed in world\n"
"bool[]                  ee_contact        # True if the foot is touching the environment\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: xpp_msgs/State6d\n"
"# The state of the 6D base of a system\n"
"\n"
"geometry_msgs/Pose     pose         # The 6D linear and angular position, orientation maps base to world\n"
"geometry_msgs/Twist    twist        # The 6D linear and angular velocity \n"
"geometry_msgs/Accel    accel        # The 6D linear and angular acceleration\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Accel\n"
"# This expresses acceleration in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: xpp_msgs/StateLin3d\n"
"# This contains the 3D representation of a linear state, including:\n"
"# position, velocity, acceleration\n"
"\n"
"geometry_msgs/Point pos\n"
"geometry_msgs/Vector3 vel\n"
"geometry_msgs/Vector3 acc\n"
;
  }

  static const char* value(const ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStateCartesianTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xpp_msgs::RobotStateCartesianTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::xpp_msgs::RobotStateCartesian_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XPP_MSGS_MESSAGE_ROBOTSTATECARTESIANTRAJECTORY_H
