(cl:defpackage xpp_msgs-msg
  (:use )
  (:export
   "<ROBOTPARAMETERS>"
   "ROBOTPARAMETERS"
   "<ROBOTSTATECARTESIAN>"
   "ROBOTSTATECARTESIAN"
   "<ROBOTSTATECARTESIANTRAJECTORY>"
   "ROBOTSTATECARTESIANTRAJECTORY"
   "<ROBOTSTATEJOINT>"
   "ROBOTSTATEJOINT"
   "<STATE6D>"
   "STATE6D"
   "<STATELIN3D>"
   "STATELIN3D"
   "<TERRAININFO>"
   "TERRAININFO"
  ))

